cico_build_ci.sh, cico_build_nightly.sh, cico_functions.sh
=> Add CI scripts for master and nightly

README.md
=> Initial docs preamble

README.md
=> trigger CI

build/Dockerfile
=> Make dockerfile a multistage build

deploy/operator.yaml, deploy/role.yaml, pkg/controller/kubernetesimagepuller/kubernetesimagepuller_controller.go
=> Check for existing deployment based on spec.deploymentName

cico_functions.sh
=> Add an operator version tag

cico_functions.sh
=> Push new operator version tag

.github/workflows/olm.yaml
=> Add an OLM GH action

README.md
=> Test OLM GH action

README.md
=> Test GH action

README.md
=> GH action test

.github/workflows/olm-bundle-release.yaml
=> Wrap expression in brackets

README.md
=> Normal branch should not trigger the GH action

deploy/olm-catalog/kubernetes-imagepuller-operator/0.0.1/kubernetes-image-puller-operator.v0.0.1.clusterserviceversion.yaml, deploy/olm-catalog/kubernetes-imagepuller-operator/0.0.1/kubernetesimagepullers.che.eclipse.org.crd.yaml, deploy/olm-catalog/kubernetes-imagepuller-operator/kubernetes-image-puller-operator.package.yaml
=> Add v0.0.1 OLM bundle

.github/workflows/olm-bundle-release.yaml
=> Adjust path for OLM bundle

deploy/olm-catalog/kubernetes-imagepuller-operator/0.0.1/kubernetes-image-puller-operator.v0.0.1.clusterserviceversion.yaml
=> Update lifecycle, example, container image, and repository

.github/workflows/olm-bundle-release.yaml
=> Correct package name

deploy/operator.yaml
=> Use eclipse/kubernetes-image-puller-operator:0.0.1 in operator.yaml

README.md, deploy/crds/che.eclipse.org_kubernetesimagepullers_crd.yaml, pkg/apis/che/v1alpha1/kubernetesimagepuller_types.go
=> Update crds and openapi

build/Dockerfile
Related to https://issues.redhat.com/browse/CRW-875
=> CRW-875 Use UBI image in kubernetes imagepuller operator

deploy/olm-catalog/kubernetes-imagepuller-operator/0.0.3/che.eclipse.org_kubernetesimagepullers_crd.yaml, deploy/olm-catalog/kubernetes-imagepuller-operator/0.0.3/kubernetes-imagepuller-operator.v0.0.3.clusterserviceversion.yaml, deploy/olm-catalog/kubernetes-imagepuller-operator/kubernetes-imagepuller-operator.package.yaml, version/version.go
=> Release operator version 0.0.3

deploy/olm-catalog/Dockerfile, deploy/olm-catalog/catalogsource.yaml, deploy/olm-catalog/kubernetes-imagepuller-operator/0.0.4/che.eclipse.org_kubernetesimagepullers_crd.yaml, deploy/olm-catalog/kubernetes-imagepuller-operator/0.0.4/kubernetes-imagepuller-operator.v0.0.4.clusterserviceversion.yaml, deploy/olm-catalog/kubernetes-imagepuller-operator/kubernetes-imagepuller-operator.package.yaml, deploy/olm-catalog/nsswitch.conf, deploy/olm-catalog/operatorgroup.yaml, deploy/olm-catalog/subscription.yaml, version/version.go
=> Update to 0.0.4, create a new CSV, add bundle registry Dockerfile, and some manifests to test operator update

deploy/crds/che.eclipse.org_kubernetesimagepullers_crd.yaml, pkg/apis/che/v1alpha1/kubernetesimagepuller_types.go, pkg/config/configmap.go, pkg/controller/kubernetesimagepuller/kubernetesimagepuller_controller_test.go
Related PR for the kubernetes image puller - https://github.com/che-incubator/kubernetes-image-puller/pull/39
=> Adding support of the image pull secrets

deploy/crds/che.eclipse.org_kubernetesimagepullers_crd.yaml, pkg/apis/che/v1alpha1/kubernetesimagepuller_types.go, pkg/config/configmap.go, pkg/controller/kubernetesimagepuller/kubernetesimagepuller_controller_test.go
Related Kubernetes Image Puller PR - https://github.com/che-incubator/kubernetes-image-puller/pull/44
=> Adding support for pod affinity

deploy/olm-catalog/kubernetes-imagepuller-operator/0.0.7/che.eclipse.org_kubernetesimagepullers_crd.yaml, deploy/olm-catalog/kubernetes-imagepuller-operator/0.0.7/kubernetes-imagepuller-operator.v0.0.7.clusterserviceversion.yaml, deploy/olm-catalog/kubernetes-imagepuller-operator/kubernetes-imagepuller-operator.package.yaml, version/version.go
=> chore(release): Releasing '0.0.7' version of the operator

.github/workflows/try-in-web-ide
https://github.com/marketplace/actions/try-in-web-ide?version=v1
=> Adding the GH action for trying the PR in web IDE

README.md
=> docs: minor README fixup

.vscode/tasks.json, README.md
Add docs about testing Prometheus metrics for kubernetes-image-puller
Signed-off-by: Oleksandr Andriienko <oandriie@redhat.com>
=> feat: Add docs about testing Prometheus metrics for kubernetes-image-puller

.github/workflows/next-build.yml, .github/workflows/olm-bundle-release.yaml, .github/workflows/release.yml, .github/workflows/try-in-web-ide.yaml
Signed-off-by: sdawley <sdawley@redhat.com>
Changes for https://github.com/eclipse/che/issues/21763
=> chore: Update ubuntu to 22.04 and actions to node 16 versions
